import { PopupThemeToken } from './types';

export const SEASONAL_THEMES: PopupThemeToken[] = [
    {
        id: 'date_new_year',
        name: 'Réveillon Gold 🥂',
        description: 'Brilhos dourados animados.',
        filterId: 'contrast',
        filterVariant: 'strong',
        overlayPreset: 'dark_soft',
        framePreset: 'floating_glow',
        specialEffect: 'sparkles',
        colors: { background: '#000000', title: '#fbbf24', body: '#d4d4d4', buttonBg: '#fbbf24', buttonText: '#000000', border: '#fbbf24' },
        recommendedFontFamily: 'Merriweather',
        recommendedImagePresentation: 'hero_single',
        defaults: { surfaceStyle: 'solid', borderRadius: 'soft', shadow: 'glow', backdrop: 'dim_strong', headerAccent: 'top_bar', spacing: 'comfortable' }
    },
    {
        id: 'date_valentines',
        name: 'Namorados ❤️',
        description: 'Corações flutuando.',
        filterId: 'saturate',
        filterVariant: 'soft',
        overlayPreset: 'vignette_soft',
        framePreset: 'rounded_modern',
        specialEffect: 'hearts',
        colors: { background: '#fff1f2', title: '#be123c', body: '#881337', buttonBg: '#e11d48', buttonText: '#ffffff' },
        recommendedFontFamily: 'Caveat',
        recommendedImagePresentation: 'stack_cards',
        defaults: { surfaceStyle: 'solid', borderRadius: 'strong', shadow: 'soft', backdrop: 'blur_soft', headerAccent: 'none', spacing: 'normal' }
    },
    {
        id: 'date_carnival',
        name: 'Carnaval Neon 🎉',
        description: 'Chuva de confetes.',
        filterId: 'saturate',
        filterVariant: 'strong',
        overlayPreset: 'none',
        framePreset: 'bold_border',
        specialEffect: 'confetti',
        colors: { background: '#2e1065', title: '#f0abfc', body: '#e9d5ff', buttonBg: '#22d3ee', buttonText: '#000000' },
        recommendedFontFamily: 'Inter',
        recommendedImagePresentation: 'collage_3',
        defaults: { surfaceStyle: 'glass', borderRadius: 'strong', shadow: 'glow', backdrop: 'dim_strong', headerAccent: 'none', spacing: 'compact' }
    },
    {
        id: 'date_easter',
        name: 'Páscoa Choco 🍫',
        description: 'Brilhos suaves.',
        filterId: 'sepia',
        filterVariant: 'soft',
        overlayPreset: 'none',
        framePreset: 'clean_border',
        specialEffect: 'sparkles',
        colors: { background: '#451a03', title: '#fcd34d', body: '#fed7aa', buttonBg: '#f59e0b', buttonText: '#ffffff' },
        recommendedFontFamily: 'Merriweather',
        recommendedImagePresentation: 'mini_slider',
        defaults: { surfaceStyle: 'solid', borderRadius: 'soft', shadow: 'strong', backdrop: 'dim_soft', headerAccent: 'badge', spacing: 'normal' }
    },
    {
        id: 'date_mothers',
        name: 'Dia das Mães 🌸',
        description: 'Luzes bokeh delicadas.',
        filterId: 'brightness',
        filterVariant: 'soft',
        overlayPreset: 'glass_blur_soft',
        framePreset: 'glass_card',
        specialEffect: 'bokeh',
        colors: { background: '#fdf2f8', title: '#db2777', body: '#831843', buttonBg: '#db2777', buttonText: '#ffffff' },
        recommendedFontFamily: 'Merriweather',
        recommendedImagePresentation: 'split_2col',
        defaults: { surfaceStyle: 'glass', borderRadius: 'full', shadow: 'soft', backdrop: 'blur_soft', headerAccent: 'none', spacing: 'comfortable' }
    },
    {
        id: 'date_fathers',
        name: 'Dia dos Pais 👔',
        description: 'Sóbrio com scanline.',
        filterId: 'contrast',
        filterVariant: 'soft',
        overlayPreset: 'dark_soft',
        framePreset: 'clean_border',
        specialEffect: 'scanline',
        colors: { background: '#1e3a8a', title: '#ffffff', body: '#bfdbfe', buttonBg: '#ffffff', buttonText: '#1e3a8a' },
        recommendedFontFamily: 'Inter',
        recommendedImagePresentation: 'hero_single',
        defaults: { surfaceStyle: 'solid', borderRadius: 'soft', shadow: 'strong', backdrop: 'dim_soft', headerAccent: 'left_bar', spacing: 'normal' }
    },
    {
        id: 'date_halloween',
        name: 'Halloween 🎃',
        description: 'Abóboras e névoa.',
        filterId: 'contrast',
        filterVariant: 'strong',
        overlayPreset: 'vignette_strong',
        framePreset: 'minimal_corner',
        specialEffect: 'pumpkins',
        colors: { background: '#1a0b2e', title: '#f97316', body: '#a855f7', buttonBg: '#f97316', buttonText: '#000000' },
        recommendedFontFamily: 'Creepster',
        recommendedImagePresentation: 'hero_single',
        defaults: { surfaceStyle: 'outline', borderRadius: 'none', shadow: 'glow', backdrop: 'dim_strong', headerAccent: 'none', spacing: 'compact' }
    },
    {
        id: 'date_christmas',
        name: 'Feliz Natal 🎄',
        description: 'Neve caindo.',
        filterId: 'contrast',
        filterVariant: 'strong',
        overlayPreset: 'vignette_soft',
        framePreset: 'rounded_modern',
        specialEffect: 'snow',
        colors: { background: '#14532d', title: '#fef2f2', body: '#bbf7d0', buttonBg: '#dc2626', buttonText: '#ffffff' },
        recommendedFontFamily: 'Merriweather',
        recommendedImagePresentation: 'stack_cards',
        defaults: { surfaceStyle: 'solid', borderRadius: 'strong', shadow: 'strong', backdrop: 'dim_soft', headerAccent: 'badge', spacing: 'normal' }
    },
];
